- name: setup the rabbitmq repo file
  ansible.builtin.copy:
    src: rabbitmq.repo
    dest: /etc/yum.repos.d/rabbitmq.repo

- name: install rabbitmq server
  ansible.builtin.dnf:
    name: rabbitmq-server
    state: present

- name: start and enable rabbitmq server
  ansible.builtin.service:
    name: rabbitmq-server
    state: started
    enabled: yes

- name: create rabbitmq user
  community.rabbitmq.rabbitmq_user:
    user: user
    password: roboshop123
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present